repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
        stages: ["pre-commit"]
