"""
Static analysis library options for the frontend UI.

This module provides predefined lists of common:
- Python imports
- C/C++ headers
- Common functions (Python / C / C++)

Used by the /static-analysis/options API endpoint.
"""

# Python common imports
PYTHON_IMPORTS = [
    # Core / DSA
    'math',
    'random',
    'itertools',
    'functools',
    'operator',
    'collections',
    'heapq',
    'bisect',
    'string',
    'statistics',
    # Timing
    'time',
    'datetime',
    # Text / parsing
    're',
    'json',
    'csv',
    # System
    'os',
    'sys',
    'pathlib',
    'subprocess',
    'shutil',
    # Typing
    'typing',
    'dataclasses',
    # Numerical / data
    'numpy',
    'pandas',
    # Visualization
    'matplotlib',
    'matplotlib.pyplot',
    # Machine learning
    'sklearn',
    'sklearn.model_selection',
    'sklearn.metrics',
    'sklearn.linear_model',
    'sklearn.neighbors',
    'sklearn.tree',
]

# C/C++ headers
CPP_HEADERS = [
    # C standard headers
    'stdio.h',
    'stdlib.h',
    'string.h',
    'math.h',
    'time.h',
    'ctype.h',
    'assert.h',
    'errno.h',
    'float.h',
    'limits.h',
    'locale.h',
    'setjmp.h',
    'signal.h',
    'stdarg.h',
    'stddef.h',
    'stdint.h',
    'stdbool.h',
    # POSIX headers
    'sys/types.h',
    'sys/stat.h',
    'fcntl.h',
    'unistd.h',
    'pthread.h',
    # C++ STL headers
    'iostream',
    'fstream',
    'sstream',
    'iomanip',
    'vector',
    'string',
    'array',
    'list',
    'forward_list',
    'deque',
    'queue',
    'stack',
    'set',
    'map',
    'unordered_set',
    'unordered_map',
    'algorithm',
    'functional',
    'iterator',
    'utility',
    'memory',
    'numeric',
    'cmath',
    'cstdlib',
    'cstring',
    'ctime',
    'bitset',
    'tuple',
    'regex',
]

# Common functions (Python / C / C++)
COMMON_FUNCTIONS = [
    # Python built-ins
    'print',
    'input',
    'eval',
    'exec',
    'open',
    'compile',
    'sorted',
    'reversed',
    'enumerate',
    'zip',
    'map',
    'filter',
    'range',
    'len',
    'sum',
    'min',
    'max',
    'abs',
    'round',
    'pow',
    'type',
    'isinstance',
    'issubclass',
    'hasattr',
    'getattr',
    'setattr',
    'delattr',
    'callable',
    'hash',
    'id',
    'repr',
    'str',
    'int',
    'float',
    'bool',
    'list',
    'dict',
    'set',
    'tuple',
    'frozenset',
    'bytes',
    'bytearray',
    'memoryview',
    'ord',
    'chr',
    'bin',
    'oct',
    'hex',
    'format',
    'vars',
    'dir',
    'globals',
    'locals',
    'help',
    '__import__',
    'breakpoint',
    'exit',
    'quit',
    # C I/O functions
    'printf',
    'scanf',
    'fprintf',
    'fscanf',
    'sprintf',
    'sscanf',
    'snprintf',
    'vprintf',
    'vfprintf',
    'vsprintf',
    'vsnprintf',
    'fopen',
    'fclose',
    'fread',
    'fwrite',
    'fgets',
    'fputs',
    'fgetc',
    'fputc',
    'getc',
    'putc',
    'getchar',
    'putchar',
    'fseek',
    'ftell',
    'rewind',
    'fflush',
    'feof',
    'ferror',
    # C string functions
    'strlen',
    'strcpy',
    'strncpy',
    'strcat',
    'strncat',
    'strcmp',
    'strncmp',
    'strchr',
    'strrchr',
    'strstr',
    'strtok',
    'memcpy',
    'memmove',
    'memset',
    'memcmp',
    'memchr',
    # C memory functions
    'malloc',
    'calloc',
    'realloc',
    'free',
    # C math functions
    'sqrt',
    'cbrt',
    'exp',
    'log',
    'log10',
    'log2',
    'sin',
    'cos',
    'tan',
    'asin',
    'acos',
    'atan',
    'atan2',
    'sinh',
    'cosh',
    'tanh',
    'ceil',
    'floor',
    'trunc',
    'fabs',
    'fmod',
    'remainder',
    'fmax',
    'fmin',
    # C utility functions
    'atoi',
    'atof',
    'atol',
    'strtol',
    'strtod',
    'strtoul',
    'rand',
    'srand',
    'qsort',
    'bsearch',
    'abort',
    'atexit',
    'system',
    'getenv',
    'setenv',
    # C++ STL algorithms
    'sort',
    'stable_sort',
    'partial_sort',
    'nth_element',
    'find',
    'find_if',
    'find_if_not',
    'count',
    'count_if',
    'search',
    'binary_search',
    'lower_bound',
    'upper_bound',
    'equal_range',
    'merge',
    'includes',
    'copy',
    'copy_if',
    'copy_n',
    'move',
    'swap',
    'fill',
    'fill_n',
    'transform',
    'replace',
    'replace_if',
    'remove',
    'remove_if',
    'unique',
    'reverse',
    'rotate',
    'shuffle',
    'random_shuffle',
    'is_sorted',
    'is_partitioned',
    'partition',
    'stable_partition',
    'min_element',
    'max_element',
    'minmax',
    'minmax_element',
    'accumulate',
    'inner_product',
    'adjacent_difference',
    'partial_sum',
    'iota',
    'gcd',
    'lcm',
    # C++ container methods (common)
    'push_back',
    'pop_back',
    'push_front',
    'pop_front',
    'push',
    'pop',
    'top',
    'front',
    'back',
    'insert',
    'erase',
    'clear',
    'empty',
    'size',
    'capacity',
    'resize',
    'reserve',
    'shrink_to_fit',
    'begin',
    'end',
    'rbegin',
    'rend',
    'cbegin',
    'cend',
    'emplace',
    'emplace_back',
    'emplace_front',
    # C++ I/O
    'cout',
    'cin',
    'cerr',
    'clog',
    'endl',
    'flush',
    'getline',
    'get',
    'put',
    'read',
    'write',
]


def get_library_symbols():
    """Return sorted, deduplicated library symbols for static analysis UI."""
    return {
        'imports': sorted(set(PYTHON_IMPORTS)),
        'headers': sorted(set(CPP_HEADERS)),
        'functions': sorted(set(COMMON_FUNCTIONS)),
    }
